"""error log table

Revision ID: 1234439ce09c
Revises: f22a91ea9807
Create Date: 2026-08-03 21:51:52.162935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1234439ce09c"
down_revision: str | Sequence[str] | None = "f22a91ea9807"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("server", "client", name="logsource", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum("error", "warning", name="loglevel", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_error_logs_created_at"), "error_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_error_logs_level"), "error_logs", ["level"], unique=False)
    op.create_index(op.f("ix_error_logs_path"), "error_logs", ["path"], unique=False)
    op.create_index(op.f("ix_error_logs_request_id"), "error_logs", ["request_id"], unique=False)
    op.create_index(op.f("ix_error_logs_source"), "error_logs", ["source"], unique=False)
    op.create_index(op.f("ix_error_logs_user_id"), "error_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_logs_user_id"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_source"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_request_id"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_path"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_level"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_created_at"), table_name="error_logs")
    op.drop_table("error_logs")
    # ### end Alembic commands ###
