"""content blocks, news and invitations

Revision ID: 67cca50b0fb8
Revises: f198069143ca
Create Date: 2026-08-03 18:41:43.588228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67cca50b0fb8"
down_revision: str | Sequence[str] | None = "f198069143ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_blocks",
        sa.Column(
            "block_type",
            sa.Enum(
                "hero",
                "features",
                "catalog",
                "about",
                "certificates",
                "contacts",
                "cta",
                "news",
                name="blocktype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("subtitle", sa.String(length=1000), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_blocks_block_type"), "content_blocks", ["block_type"], unique=False
    )
    op.create_index(
        op.f("ix_content_blocks_sort_order"), "content_blocks", ["sort_order"], unique=False
    )
    op.create_table(
        "news_posts",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "news", "promo", "announcement", name="postcategory", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_posts_category"), "news_posts", ["category"], unique=False)
    op.create_index(
        op.f("ix_news_posts_is_published"), "news_posts", ["is_published"], unique=False
    )
    op.create_index(
        op.f("ix_news_posts_published_at"), "news_posts", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_news_posts_slug"), "news_posts", ["slug"], unique=True)
    op.create_table(
        "user_invitations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "invite", "password_reset", name="invitationpurpose", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_invitations_email"), "user_invitations", ["email"], unique=False)
    op.create_index(
        op.f("ix_user_invitations_token_hash"), "user_invitations", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_user_invitations_user_id"), "user_invitations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_invitations_user_id"), table_name="user_invitations")
    op.drop_index(op.f("ix_user_invitations_token_hash"), table_name="user_invitations")
    op.drop_index(op.f("ix_user_invitations_email"), table_name="user_invitations")
    op.drop_table("user_invitations")
    op.drop_index(op.f("ix_news_posts_slug"), table_name="news_posts")
    op.drop_index(op.f("ix_news_posts_published_at"), table_name="news_posts")
    op.drop_index(op.f("ix_news_posts_is_published"), table_name="news_posts")
    op.drop_index(op.f("ix_news_posts_category"), table_name="news_posts")
    op.drop_table("news_posts")
    op.drop_index(op.f("ix_content_blocks_sort_order"), table_name="content_blocks")
    op.drop_index(op.f("ix_content_blocks_block_type"), table_name="content_blocks")
    op.drop_table("content_blocks")
    # ### end Alembic commands ###
