"""routes and visits

Revision ID: 729ef3a113c6
Revises: b3aaee26248b
Create Date: 2026-08-04 07:52:50.090926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "729ef3a113c6"
down_revision: str | Sequence[str] | None = "b3aaee26248b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("sales_rep_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sales_rep_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_code"), "routes", ["code"], unique=False)
    op.create_index(op.f("ix_routes_name"), "routes", ["name"], unique=False)
    op.create_index(op.f("ix_routes_sales_rep_id"), "routes", ["sales_rep_id"], unique=False)
    op.create_table(
        "route_stops",
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("weekdays", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "outlet_id", name="uq_route_stop"),
    )
    op.create_index(op.f("ix_route_stops_outlet_id"), "route_stops", ["outlet_id"], unique=False)
    op.create_index(op.f("ix_route_stops_route_id"), "route_stops", ["route_id"], unique=False)
    op.create_table(
        "visits",
        sa.Column("outlet_id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=True),
        sa.Column("sales_rep_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "planned",
                "order",
                "no_order",
                "closed",
                "refused",
                "skipped",
                name="visitresult",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sales_rep_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sales_rep_id", "outlet_id", "planned_date", name="uq_visit_per_day"),
    )
    op.create_index(op.f("ix_visits_outlet_id"), "visits", ["outlet_id"], unique=False)
    op.create_index(op.f("ix_visits_planned_date"), "visits", ["planned_date"], unique=False)
    op.create_index(op.f("ix_visits_result"), "visits", ["result"], unique=False)
    op.create_index(op.f("ix_visits_route_id"), "visits", ["route_id"], unique=False)
    op.create_index(op.f("ix_visits_sales_rep_id"), "visits", ["sales_rep_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visits_sales_rep_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_route_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_result"), table_name="visits")
    op.drop_index(op.f("ix_visits_planned_date"), table_name="visits")
    op.drop_index(op.f("ix_visits_outlet_id"), table_name="visits")
    op.drop_table("visits")
    op.drop_index(op.f("ix_route_stops_route_id"), table_name="route_stops")
    op.drop_index(op.f("ix_route_stops_outlet_id"), table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index(op.f("ix_routes_sales_rep_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_name"), table_name="routes")
    op.drop_index(op.f("ix_routes_code"), table_name="routes")
    op.drop_table("routes")
    # ### end Alembic commands ###
