"""mail settings in system settings

Revision ID: 9d04eebac2d0
Revises: 4053d0c2fbe4
Create Date: 2026-08-05 15:03:54.437368

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d04eebac2d0"
down_revision: str | Sequence[str] | None = "4053d0c2fbe4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_settings", sa.Column("smtp_host", sa.String(length=200), nullable=True))
    # server_default обязателен: строка настроек уже существует, и без
    # значения по умолчанию обязательную колонку к ней не добавить.
    op.add_column(
        "app_settings", sa.Column("smtp_port", sa.Integer(), nullable=False, server_default="587")
    )
    op.add_column("app_settings", sa.Column("smtp_user", sa.String(length=200), nullable=True))
    op.add_column(
        "app_settings", sa.Column("smtp_password_enc", sa.String(length=500), nullable=True)
    )
    op.add_column("app_settings", sa.Column("smtp_from", sa.String(length=200), nullable=True))
    op.add_column(
        "app_settings",
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "app_settings",
        sa.Column("smtp_use_ssl", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "smtp_use_ssl")
    op.drop_column("app_settings", "smtp_use_tls")
    op.drop_column("app_settings", "smtp_from")
    op.drop_column("app_settings", "smtp_password_enc")
    op.drop_column("app_settings", "smtp_user")
    op.drop_column("app_settings", "smtp_port")
    op.drop_column("app_settings", "smtp_host")
    # ### end Alembic commands ###
