"""product page fields

Revision ID: 9f4d8c958a54
Revises: 9d04eebac2d0
Create Date: 2026-08-06 09:03:24.700188

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f4d8c958a54"
down_revision: str | Sequence[str] | None = "9d04eebac2d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен для обеих: таблица не пуста, а колонки
    # обязательные — без значения по умолчанию их к ней не добавить.
    op.add_column(
        "nomenclature",
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("nomenclature", sa.Column("slug", sa.String(length=200), nullable=True))
    op.add_column("nomenclature", sa.Column("image_url", sa.String(length=500), nullable=True))
    op.add_column("nomenclature", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("nomenclature", sa.Column("composition", sa.Text(), nullable=True))
    op.add_column("nomenclature", sa.Column("shelf_life", sa.String(length=200), nullable=True))
    op.add_column("nomenclature", sa.Column("storage", sa.String(length=300), nullable=True))
    op.add_column("nomenclature", sa.Column("pack", sa.String(length=200), nullable=True))
    op.add_column(
        "nomenclature",
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.create_index(
        op.f("ix_nomenclature_is_published"), "nomenclature", ["is_published"], unique=False
    )
    op.create_index(op.f("ix_nomenclature_slug"), "nomenclature", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nomenclature_slug"), table_name="nomenclature")
    op.drop_index(op.f("ix_nomenclature_is_published"), table_name="nomenclature")
    op.drop_column("nomenclature", "translations")
    op.drop_column("nomenclature", "pack")
    op.drop_column("nomenclature", "storage")
    op.drop_column("nomenclature", "shelf_life")
    op.drop_column("nomenclature", "composition")
    op.drop_column("nomenclature", "description")
    op.drop_column("nomenclature", "image_url")
    op.drop_column("nomenclature", "slug")
    op.drop_column("nomenclature", "is_published")
    # ### end Alembic commands ###
