"""stock documents and movements

Revision ID: 9f9b099350c4
Revises: 10a3d23164ee
Create Date: 2026-08-03 23:34:35.434860

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f9b099350c4"
down_revision: str | Sequence[str] | None = "10a3d23164ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Автогенерация не создаёт последовательность, на которую ссылается
    # server_default колонки stock_documents.number.
    op.execute(sa.schema.CreateSequence(sa.Sequence("stock_document_number_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_documents",
        sa.Column(
            "number",
            sa.Integer(),
            server_default=sa.text("nextval('stock_document_number_seq')"),
            nullable=False,
        ),
        sa.Column(
            "document_type",
            sa.Enum(
                "receipt",
                "writeoff",
                "inventory",
                "shipment",
                name="stockdocumenttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "posted", name="stockdocumentstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "document_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(
        op.f("ix_stock_documents_document_date"), "stock_documents", ["document_date"], unique=False
    )
    op.create_index(
        op.f("ix_stock_documents_document_type"), "stock_documents", ["document_type"], unique=False
    )
    op.create_index(
        op.f("ix_stock_documents_order_id"), "stock_documents", ["order_id"], unique=False
    )
    op.create_index(op.f("ix_stock_documents_status"), "stock_documents", ["status"], unique=False)
    op.create_index(
        op.f("ix_stock_documents_warehouse_id"), "stock_documents", ["warehouse_id"], unique=False
    )
    op.create_table(
        "stock_document_lines",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("nomenclature_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("expected_quantity", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["stock_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["nomenclature_id"], ["nomenclature.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_document_lines_document_id"),
        "stock_document_lines",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_document_lines_nomenclature_id"),
        "stock_document_lines",
        ["nomenclature_id"],
        unique=False,
    )
    op.create_table(
        "stock_movements",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("nomenclature_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column(
            "moved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["stock_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["nomenclature_id"], ["nomenclature.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_document_id"), "stock_movements", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_moved_at"), "stock_movements", ["moved_at"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_nomenclature_id"),
        "stock_movements",
        ["nomenclature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_warehouse_id"), "stock_movements", ["warehouse_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_warehouse_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_nomenclature_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_moved_at"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_document_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(
        op.f("ix_stock_document_lines_nomenclature_id"), table_name="stock_document_lines"
    )
    op.drop_index(op.f("ix_stock_document_lines_document_id"), table_name="stock_document_lines")
    op.drop_table("stock_document_lines")
    op.drop_index(op.f("ix_stock_documents_warehouse_id"), table_name="stock_documents")
    op.drop_index(op.f("ix_stock_documents_status"), table_name="stock_documents")
    op.drop_index(op.f("ix_stock_documents_order_id"), table_name="stock_documents")
    op.drop_index(op.f("ix_stock_documents_document_type"), table_name="stock_documents")
    op.drop_index(op.f("ix_stock_documents_document_date"), table_name="stock_documents")
    op.drop_table("stock_documents")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("stock_document_number_seq")))
