"""counterparty 2gis link

Revision ID: aeac3a55fbde
Revises: eed159d40361
Create Date: 2026-08-04 09:58:48.365236

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeac3a55fbde"
down_revision: str | Sequence[str] | None = "eed159d40361"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("counterparties", sa.Column("dgis_url", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("counterparties", "dgis_url")
    # ### end Alembic commands ###
