"""payments and settlements

Revision ID: b3aaee26248b
Revises: 9f9b099350c4
Create Date: 2026-08-04 00:07:53.707611

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3aaee26248b"
down_revision: str | Sequence[str] | None = "9f9b099350c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Автогенерация не создаёт последовательность для номера оплаты.
    op.execute(sa.schema.CreateSequence(sa.Sequence("payment_number_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column(
            "number",
            sa.Integer(),
            server_default=sa.text("nextval('payment_number_seq')"),
            nullable=False,
        ),
        sa.Column(
            "payment_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("counterparty_id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column(
            "method",
            sa.Enum("cash", "bank", "card", name="paymentmethod", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["counterparty_id"], ["counterparties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(op.f("ix_payments_contract_id"), "payments", ["contract_id"], unique=False)
    op.create_index(
        op.f("ix_payments_counterparty_id"), "payments", ["counterparty_id"], unique=False
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_payment_date"), "payments", ["payment_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_payment_date"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_counterparty_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_contract_id"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("payment_number_seq")))
