"""storage settings in system settings

Revision ID: e68d862e2cf2
Revises: 9f4d8c958a54
Create Date: 2026-08-06 09:32:31.133365

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e68d862e2cf2"
down_revision: str | Sequence[str] | None = "9f4d8c958a54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_settings", sa.Column("s3_bucket", sa.String(length=200), nullable=True))
    op.add_column(
        "app_settings", sa.Column("s3_endpoint_url", sa.String(length=500), nullable=True)
    )
    op.add_column("app_settings", sa.Column("s3_region", sa.String(length=50), nullable=True))
    op.add_column("app_settings", sa.Column("s3_access_key", sa.String(length=200), nullable=True))
    op.add_column(
        "app_settings", sa.Column("s3_secret_key_enc", sa.String(length=500), nullable=True)
    )
    op.add_column("app_settings", sa.Column("s3_public_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "s3_public_url")
    op.drop_column("app_settings", "s3_secret_key_enc")
    op.drop_column("app_settings", "s3_access_key")
    op.drop_column("app_settings", "s3_region")
    op.drop_column("app_settings", "s3_endpoint_url")
    op.drop_column("app_settings", "s3_bucket")
    # ### end Alembic commands ###
