"""price types and discounts

Revision ID: eed159d40361
Revises: ff0ccdbc1a01
Create Date: 2026-08-04 09:30:31.467929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eed159d40361"
down_revision: Union[str, Sequence[str], None] = "ff0ccdbc1a01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_types",
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_types_code"), "price_types", ["code"], unique=False)
    op.create_index(op.f("ix_price_types_is_default"), "price_types", ["is_default"], unique=False)
    op.create_index(op.f("ix_price_types_name"), "price_types", ["name"], unique=False)
    op.create_table(
        "prices",
        sa.Column("nomenclature_id", sa.Uuid(), nullable=False),
        sa.Column("price_type_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["nomenclature_id"], ["nomenclature.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["price_type_id"], ["price_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nomenclature_id", "price_type_id", name="uq_price_per_type"),
    )
    op.create_index(op.f("ix_prices_nomenclature_id"), "prices", ["nomenclature_id"], unique=False)
    op.create_index(op.f("ix_prices_price_type_id"), "prices", ["price_type_id"], unique=False)
    op.add_column("contracts", sa.Column("price_type_id", sa.Uuid(), nullable=True))
    op.add_column(
        # У существующих договоров скидки нет — нужен server_default,
        # иначе колонку NOT NULL не добавить к непустой таблице.
        "contracts",
        sa.Column(
            "discount_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default="0",
        ),
    )
    op.create_foreign_key(
        None, "contracts", "price_types", ["price_type_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contracts", type_="foreignkey")
    op.drop_column("contracts", "discount_percent")
    op.drop_column("contracts", "price_type_id")
    op.drop_index(op.f("ix_prices_price_type_id"), table_name="prices")
    op.drop_index(op.f("ix_prices_nomenclature_id"), table_name="prices")
    op.drop_table("prices")
    op.drop_index(op.f("ix_price_types_name"), table_name="price_types")
    op.drop_index(op.f("ix_price_types_is_default"), table_name="price_types")
    op.drop_index(op.f("ix_price_types_code"), table_name="price_types")
    op.drop_table("price_types")
    # ### end Alembic commands ###
