"""initial schema

Revision ID: f198069143ca
Revises:
Create Date: 2026-08-03 18:35:58.594476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f198069143ca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Автогенерация не создаёт последовательность, на которую ссылается
    # server_default колонки orders.number, — заводим её явно до таблиц.
    op.execute(sa.schema.CreateSequence(sa.Sequence("order_number_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("logo_dark_url", sa.String(length=500), nullable=True),
        sa.Column("favicon_url", sa.String(length=500), nullable=True),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("accent_color", sa.String(length=7), nullable=False),
        sa.Column("hero_title", sa.String(length=300), nullable=True),
        sa.Column("hero_subtitle", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "counterparties",
        sa.Column("full_name", sa.String(length=1000), nullable=True),
        sa.Column("bin_iin", sa.String(length=12), nullable=True),
        sa.Column("is_legal_entity", sa.Boolean(), nullable=False),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_counterparties_bin_iin"), "counterparties", ["bin_iin"], unique=False)
    op.create_index(op.f("ix_counterparties_code"), "counterparties", ["code"], unique=False)
    op.create_index(op.f("ix_counterparties_name"), "counterparties", ["name"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("full_name", sa.String(length=1000), nullable=True),
        sa.Column("bin", sa.String(length=12), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_code"), "organizations", ["code"], unique=False)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "outlet_types",
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outlet_types_code"), "outlet_types", ["code"], unique=False)
    op.create_index(op.f("ix_outlet_types_name"), "outlet_types", ["name"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["product_categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_categories_code"), "product_categories", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_product_categories_name"), "product_categories", ["name"], unique=False
    )
    op.create_table(
        "units_of_measure",
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("okei_code", sa.String(length=10), nullable=True),
        sa.Column("ratio", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_of_measure_code"), "units_of_measure", ["code"], unique=False)
    op.create_index(op.f("ix_units_of_measure_name"), "units_of_measure", ["name"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("counterparty_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.String(length=100), nullable=True),
        sa.Column("contract_date", sa.Date(), nullable=True),
        sa.Column("payment_days", sa.Integer(), nullable=False),
        sa.Column("credit_limit", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["counterparty_id"], ["counterparties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_code"), "contracts", ["code"], unique=False)
    op.create_index(op.f("ix_contracts_name"), "contracts", ["name"], unique=False)
    op.create_table(
        "divisions",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["divisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_divisions_code"), "divisions", ["code"], unique=False)
    op.create_index(op.f("ix_divisions_name"), "divisions", ["name"], unique=False)
    op.create_table(
        "nomenclature",
        sa.Column("full_name", sa.String(length=1000), nullable=True),
        sa.Column("article", sa.String(length=100), nullable=True),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("base_unit_id", sa.Uuid(), nullable=True),
        sa.Column("is_weight_goods", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["base_unit_id"], ["units_of_measure.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["product_categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nomenclature_article"), "nomenclature", ["article"], unique=False)
    op.create_index(op.f("ix_nomenclature_barcode"), "nomenclature", ["barcode"], unique=False)
    op.create_index(op.f("ix_nomenclature_code"), "nomenclature", ["code"], unique=False)
    op.create_index(op.f("ix_nomenclature_name"), "nomenclature", ["name"], unique=False)
    op.create_table(
        "warehouses",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_warehouses_code"), "warehouses", ["code"], unique=False)
    op.create_index(op.f("ix_warehouses_name"), "warehouses", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "manager",
                "sales_rep",
                "warehouse",
                name="userrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("division_id", sa.Uuid(), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "outlets",
        sa.Column("counterparty_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_type_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("sales_rep_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["counterparty_id"], ["counterparties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["outlet_type_id"], ["outlet_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sales_rep_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outlets_code"), "outlets", ["code"], unique=False)
    op.create_index(
        op.f("ix_outlets_counterparty_id"), "outlets", ["counterparty_id"], unique=False
    )
    op.create_index(op.f("ix_outlets_name"), "outlets", ["name"], unique=False)
    op.create_index(op.f("ix_outlets_outlet_type_id"), "outlets", ["outlet_type_id"], unique=False)
    op.create_index(op.f("ix_outlets_sales_rep_id"), "outlets", ["sales_rep_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column(
            "number",
            sa.Integer(),
            server_default=sa.text("nextval('order_number_seq')"),
            nullable=False,
        ),
        sa.Column(
            "order_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "new",
                "assembling",
                "assembled",
                "shipped",
                "delivered",
                "cancelled",
                name="orderstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("division_id", sa.Uuid(), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("counterparty_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_address", sa.String(length=1000), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["counterparty_id"], ["counterparties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(op.f("ix_orders_author_id"), "orders", ["author_id"], unique=False)
    op.create_index(op.f("ix_orders_delivery_date"), "orders", ["delivery_date"], unique=False)
    op.create_index(op.f("ix_orders_outlet_id"), "orders", ["outlet_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_warehouse_id"), "orders", ["warehouse_id"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("nomenclature_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("quantity_shipped", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["nomenclature_id"], ["nomenclature.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units_of_measure.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_lines_order_id"), "order_lines", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_orders_warehouse_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_outlet_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_delivery_date"), table_name="orders")
    op.drop_index(op.f("ix_orders_author_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_outlets_sales_rep_id"), table_name="outlets")
    op.drop_index(op.f("ix_outlets_outlet_type_id"), table_name="outlets")
    op.drop_index(op.f("ix_outlets_name"), table_name="outlets")
    op.drop_index(op.f("ix_outlets_counterparty_id"), table_name="outlets")
    op.drop_index(op.f("ix_outlets_code"), table_name="outlets")
    op.drop_table("outlets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_warehouses_name"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_code"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index(op.f("ix_nomenclature_name"), table_name="nomenclature")
    op.drop_index(op.f("ix_nomenclature_code"), table_name="nomenclature")
    op.drop_index(op.f("ix_nomenclature_barcode"), table_name="nomenclature")
    op.drop_index(op.f("ix_nomenclature_article"), table_name="nomenclature")
    op.drop_table("nomenclature")
    op.drop_index(op.f("ix_divisions_name"), table_name="divisions")
    op.drop_index(op.f("ix_divisions_code"), table_name="divisions")
    op.drop_table("divisions")
    op.drop_index(op.f("ix_contracts_name"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_code"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_units_of_measure_name"), table_name="units_of_measure")
    op.drop_index(op.f("ix_units_of_measure_code"), table_name="units_of_measure")
    op.drop_table("units_of_measure")
    op.drop_index(op.f("ix_product_categories_name"), table_name="product_categories")
    op.drop_index(op.f("ix_product_categories_code"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_outlet_types_name"), table_name="outlet_types")
    op.drop_index(op.f("ix_outlet_types_code"), table_name="outlet_types")
    op.drop_table("outlet_types")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_code"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_counterparties_name"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_code"), table_name="counterparties")
    op.drop_index(op.f("ix_counterparties_bin_iin"), table_name="counterparties")
    op.drop_table("counterparties")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("order_number_seq")))
