"""customer returns

Revision ID: ff0ccdbc1a01
Revises: 729ef3a113c6
Create Date: 2026-08-04 09:11:50.385593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff0ccdbc1a01"
down_revision: str | Sequence[str] | None = "729ef3a113c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Автогенерация не создаёт последовательность для номера возврата.
    op.execute(sa.schema.CreateSequence(sa.Sequence("return_number_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "returns",
        sa.Column(
            "number",
            sa.Integer(),
            server_default=sa.text("nextval('return_number_seq')"),
            nullable=False,
        ),
        sa.Column("return_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "posted", name="returnstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("counterparty_id", sa.Uuid(), nullable=False),
        sa.Column("outlet_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "expired",
                "defect",
                "surplus",
                "misgrade",
                "other",
                name="returnreason",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["counterparty_id"], ["counterparties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(
        op.f("ix_returns_counterparty_id"), "returns", ["counterparty_id"], unique=False
    )
    op.create_index(op.f("ix_returns_order_id"), "returns", ["order_id"], unique=False)
    op.create_index(op.f("ix_returns_reason"), "returns", ["reason"], unique=False)
    op.create_index(op.f("ix_returns_return_date"), "returns", ["return_date"], unique=False)
    op.create_index(op.f("ix_returns_status"), "returns", ["status"], unique=False)
    op.create_index(op.f("ix_returns_warehouse_id"), "returns", ["warehouse_id"], unique=False)
    op.create_table(
        "return_lines",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("nomenclature_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["nomenclature_id"], ["nomenclature.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["return_id"], ["returns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_return_lines_nomenclature_id"), "return_lines", ["nomenclature_id"], unique=False
    )
    op.create_index(op.f("ix_return_lines_return_id"), "return_lines", ["return_id"], unique=False)
    op.add_column("stock_documents", sa.Column("return_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_stock_documents_return_id"), "stock_documents", ["return_id"], unique=False
    )
    op.create_foreign_key(
        None, "stock_documents", "returns", ["return_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_documents", type_="foreignkey")
    op.drop_index(op.f("ix_stock_documents_return_id"), table_name="stock_documents")
    op.drop_column("stock_documents", "return_id")
    op.drop_index(op.f("ix_return_lines_return_id"), table_name="return_lines")
    op.drop_index(op.f("ix_return_lines_nomenclature_id"), table_name="return_lines")
    op.drop_table("return_lines")
    op.drop_index(op.f("ix_returns_warehouse_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_status"), table_name="returns")
    op.drop_index(op.f("ix_returns_return_date"), table_name="returns")
    op.drop_index(op.f("ix_returns_reason"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_counterparty_id"), table_name="returns")
    op.drop_table("returns")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("return_number_seq")))
